twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
        # Inport bootstrap theme form
        form_themes: ['bootstrap_5_layout.html.twig']

        # pour un custom des input du formualire personnalis√©
        # form_themes: ['form/register_theme.html.twig']

